# fly.toml app configuration file generated for broken-glade-6034 on 2023-07-31T22:57:25+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "broken-glade-6034"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
